### ISSUE TITLE
Material Slots ?

### ISSUE THREAD

**Issue by melMass** [sideeffects/HoudiniEngineForUnreal#102]
Is there a reason why we cannot use a dropdown slot for materials as we can for meshes ?

I use the `copy reference path` trick but it's unstable and not user-friendly.

**Comment by dpernuit** [comment]
Hi,

On the output side of the plugin, we do create materials slots for the generated mesh, so I assume you're referring to string parameters on the input side of things? 

If that's the case, for now, we simply cant make a difference between a string parameter that you intend to use for a material, or for an asset ref, or just to input text...

Version 2 of the plugin will offer some improvements on this, where string parameters will automatically read the asset ref of asset that are dropped onto them, and offer the possibility to be converted to asset pickers via the use of special tags on the parameter.

**Comment by melMass** [comment]
Exactly, a parameter tag to specify the asset type would be perfect yes!

**Comment by dpernuit** [comment]
Closing - Multiple materials slots supports on point instancers was added in H19.5
