### ISSUE TITLE
multiparm UI bug

### ISSUE THREAD

**Issue by Lambda-li** [sideeffects/HoudiniEngineForUnreal#103]
When HDA uses the multiparm UI to delete intermediate data, the UI data behind the deleted data is garbled or lost.（Unreal 4.21.2 and Houdini 17.5.229）

![image](https://user-images.githubusercontent.com/18109883/63479462-fd109c80-c4c0-11e9-8068-0b4b3209a198.png)

**Comment by dpernuit** [comment]
Hi,
Thank you for reporting this, we're aware that multiparms do have some bugs on version1 of the plugin. They have been fixed in version 2, but we unfortunately  wont be able to backport the changes to v1.
