### ISSUE TITLE
Support additional handle types (beyond 'xform')

### ISSUE THREAD

**Issue by JaapSuter** [sideeffects/HoudiniEngineForUnreal#11]
Per https://www.sidefx.com/index.php?option=com_forum&Itemid=172&page=viewtopic&t=43008&sid=efc6341a0aac32de108bc58c6949441f

If I understand correctly, the only handle type that is currently supported is the plain transform node (xform). The plugin code seems to filter for that. I realize that not all of the Houdini handles map to Unreal's default transform widget, but I'm wondering how much work it'd be to add support for the ones that do map. 

For example, if I extrude a grid or a closed polygon, the mesh shows up in Unreal. I'd like to be able to then grab the grid corners, or the curve vertices, and move them around in Unreal (rotate and scale wouldn't make much sense there, but it wouldn't bother me if those showed up as possible). 

I've attached an HDA [extruded_grid.zip](https://github.com/sideeffects/HoudiniEngineForUnreal/files/91214/extruded_grid.zip) (zipped, because GitHub won't allow upload of HDA directly) that has an extruded grid with handles for the grid shape and the actual extrusion. Do you see it feasible to have handles such as these show up in Unreal?

**Comment by ttvd** [comment]
It should be possible for us to support more types of handles, beyond xform; we'll look into it :)

Unreal uses a single gizmo for everything (I think it's a singleton object, so you can't have two gizmos active at the same time), but when switching between instances, you can tell which modes you want enabled - translate, rotate, scale. So you can create a handle with just a translate component.

**Comment by cgrebeld** [comment]
Doesn't address your use case, but FYI we added support for the 'bounder' handle awhile ago:
http://www.sidefx.com/docs/unreal16.0/_handles.html

There are so many handles in Houdini, if there's a really useful one you'd like to see supported in the plugin I suggest submitting an RFE to sidefx.
