### ISSUE TITLE
17.5.402 is not available to download.

### ISSUE THREAD

**Issue by pixelscience** [sideeffects/HoudiniEngineForUnreal#110]
I was trying to compile the plugin, but Houdini 17.5.402 is not listed on the daily builds section anymore and is not in the ftp.

**Comment by dpernuit** [comment]
Hi,

This is an unfortunate consequence of the way our github is automatically updated, as it's only updated when changes are commited to the plugin.

If the version specified in the plugin's build.cs file is not available for download, you can simply use the latest daily build, and change the version numbers in HoudiniEngineRuntime.build.cs and HoudiniEngineEditor.build.cs.

**Comment by pixelscience** [comment]
I got it working on linux with 17.5.416! Thanks for the help.
