### ISSUE TITLE
Materials reference material functions inside a developer folder

### ISSUE THREAD

**Issue by petergiuntoli** [sideeffects/HoudiniEngineForUnreal#115]
We're working on updating houdini and we're noticing some errors and warnings coming from houdini content.  Specifically it looks like multiple materials inside `HoudiniEngine/Materials/*` reference content in a "mikel" developer folder which produces errors like the following when trying to open those materials:

`LoadErrors: Failed to load /Game/Developers/mikel/VAT/MaterialFunctions/MF_VAT_Fluid.MF_VAT_Fluid Referenced by M_VAT_Fluid`
`LoadErrors: Failed to load /Game/Developers/mikel/VAT/MaterialFunctions/MF_VAT_Fluid.MF_VAT_Fluid Referenced by MaterialExpressionMaterialFunctionCall_0`
`LogLinker: Warning: While loading '../../Plugins/Runtime/HoudiniEngine/Content/Materials/M_VAT_Fluid.uasset' failed to load '/Game/Developers/mikel/VAT/MaterialFunctions/MF_VAT_Fluid': Can't find file.`

We fixed this locally by creating a package redirect and resaving the materials.

`PackageRedirects=(OldName="/Game/Developers/mikel/VAT/MaterialFunctions/MF_VAT_Fluid",NewName="/HoudiniEngine/MaterialFunctions/MF_VAT_Fluid")`
`PackageRedirects=(OldName="/Game/Developers/mikel/VAT/MaterialFunctions/MF_VAT_Rigid",NewName="/HoudiniEngine/MaterialFunctions/MF_VAT_Rigid")`
`PackageRedirects=(OldName="/Game/Developers/mikel/VAT/MaterialFunctions/MF_VAT_Soft",NewName="/HoudiniEngine/MaterialFunctions/MF_VAT_Soft")`
`PackageRedirects=(OldName="/Game/Developers/mikel/VAT/MaterialFunctions/MF_VAT_Sprite",NewName="/HoudiniEngine/MaterialFunctions/MF_VAT_Sprite")`

**Comment by dpernuit** [comment]
I've just committed an update for the VAT2.0 that shouldn't have this issue.
The fix will be available here tomorrow, or in tomorrow's daily build of Houdini.

**Comment by petergiuntoli** [comment]
@dpernuit I'm assuming this is fixed, do you want to close the issue?
