### ISSUE TITLE
Compile warnings on 4.24

### ISSUE THREAD

**Issue by huwb** [sideeffects/HoudiniEngineForUnreal#116]
Hello, I'm not sure if this was worth creating an issue for, forgive me if not.

Just thought I'd register that we're getting warnings when building against 4.24, and check if there is a rough timeline on fixes so we can decide whether to fix ourselves?

Put a (redacted) dump of the warnings below:

`
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniLandscapeUtils.cpp(856): warning C4996: The ARRAY_COUNT macro has been deprecated in favor of UE_ARRAY_COUNT. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniLandscapeUtils.cpp(858): warning C4996: The ARRAY_COUNT macro has been deprecated in favor of UE_ARRAY_COUNT. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniLandscapeUtils.cpp(886): warning C4996: The ARRAY_COUNT macro has been deprecated in favor of UE_ARRAY_COUNT. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniLandscapeUtils.cpp(910): warning C4996: The ARRAY_COUNT macro has been deprecated in favor of UE_ARRAY_COUNT. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniLandscapeUtils.cpp(911): warning C4996: The ARRAY_COUNT macro has been deprecated in favor of UE_ARRAY_COUNT. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniAssetActor.cpp(45): warning C4996: 'AActor::bCanBeDamaged': This member will be made private. Please use CanBeDamaged or SetCanBeDamaged. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(280): note: see declaration of 'AActor::bCanBeDamaged'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniAssetComponent.cpp(2454): warning C4996: 'USceneComponent::bVisible': This member will be made private. Please use IsVisible or SetVisibility. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(204): note: see declaration of 'USceneComponent::bVisible'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniAssetComponent.cpp(3434): warning C4996: 'AActor::GetComponentsByClass': Use one of the GetComponents implementations as appropriate Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(2909): note: see declaration of 'AActor::GetComponentsByClass'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniAssetInput.cpp(3534): warning C4996: 'AActor::GetComponentsByClass': Use one of the GetComponents implementations as appropriate Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(2909): note: see declaration of 'AActor::GetComponentsByClass'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniAssetInput.cpp(3586): warning C4996: 'AActor::GetComponentsByClass': Use one of the GetComponents implementations as appropriate Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\GameFramework/Actor.h(2909): note: see declaration of 'AActor::GetComponentsByClass'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniEngineBakeUtils.cpp(365): warning C4996: 'USceneComponent::RelativeLocation': This member will be made private. Please use GetRelativeLocation or SetRelativeLocation. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(154): note: see declaration of 'USceneComponent::RelativeLocation'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniEngineBakeUtils.cpp(366): warning C4996: 'USceneComponent::RelativeRotation': This member will be made private. Please use GetRelativeRotation or SetRelativeRotation. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(159): note: see declaration of 'USceneComponent::RelativeRotation'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniEngineBakeUtils.cpp(1947): warning C4996: 'UEditorEngine::Layers': ILayers and FLayers (GEditor->Layers) have been deprecated, use ULayersSubsystem (rather than ILayers) and GEditor->GetEditorSubsystem<ULayersSubsystem>() (rather than GEditor->Layers) instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Editor\UnrealEd\Classes\Editor/EditorEngine.h(737): note: see declaration of 'UEditorEngine::Layers'
/Engine/Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineEditor/Private/RiverAssetComponent.cpp(389): warning C4996: 'USceneComponent::bVisible': This member will be made private. Please use IsVisible or SetVisibility. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
 \Engine\Source\Runtime\Engine\Classes\Components/SceneComponent.h(204): note: see declaration of 'USceneComponent::bVisible'
`

**Comment by melMass** [comment]
Dumb question, but are you using the 4.24 branch?

**Comment by huwb** [comment]
Hello, yes we are.

**Comment by dpernuit** [comment]
Hi,

You may want to try again, as it does seems that you were not using the 4.24 sources.
All those warnings/deprecation messages were fixed in the first commit that I did after I created the 4.24 branch.

See:
https://github.com/sideeffects/HoudiniEngineForUnreal/commit/12a73ea95ea248e0a6b2faeb72d7b03a9c26d05f#diff-f31bbdd1b3e85bccd652680e16935819

and

https://github.com/sideeffects/HoudiniEngineForUnreal/commit/6c648694760ca815a132148a70ba0bcd8fea9e90#diff-f31bbdd1b3e85bccd652680e16935819

**Comment by huwb** [comment]
Sorry I misunderstood which branch the above referred to and was a bit confused! Thanks for the replies and commit references!
