### ISSUE TITLE
V2 Beta ETA ?

### ISSUE THREAD

**Issue by melMass** [sideeffects/HoudiniEngineForUnreal#117]
Hi,

I really need a way to input AND output curves from an HDA, I know it's on the roadmap for V2 but I also heard it was delayed quite a bit?
Is there a plan to start an open or closed beta of the new version at some point?
I'm forking the repo now to try to add it myself to v1 in the meantime 

Thanks

**Comment by dpernuit** [comment]
Hi,
That's correct, we're spending a little more time on V2 than originally planned.
We do plan on having a public beta of the plugin, the current estimate for it is end of March/April.
