### ISSUE TITLE
Using PDG in HDA will cause a fatal error and a crash in UE5

### ISSUE THREAD

**Issue by dearamy** [sideeffects/HoudiniEngineForUnreal#147]
we are using the github 5.0 ue5 and houdini engine with 6ceb0bcff17214d65b11aec59ab53d4b8300a096. 
And the crash info was like the screenshot below
![image](https://user-images.githubusercontent.com/6821403/149453764-2cbae342-b636-40fe-8d26-f9e95dd22230.png)

**Comment by mchamberlain** [comment]
This issue should be fixed in a90d677ba0294f3b2754e45fcc67e1448c26a67c.
