### ISSUE TITLE
Large landscape will cause a Houdini Engine Session lost 

### ISSUE THREAD

**Issue by dearamy** [sideeffects/HoudiniEngineForUnreal#149]
There's a Houdini Engine Session Lost when convert a large landscape to Houdini. I've tried some values, basically, when FloatValues's num is larger than 20,000,000, houdini_check will return a "Houdini Engine Session lost Error". 
![image](https://user-images.githubusercontent.com/6821403/151504431-028779fc-e7e4-459c-807f-4c00df1ab935.png)

**Comment by dpernuit** [comment]
Hi,
This issue has been fixed a while ago.
The main issue was an update in the thrift library that we use for RPC, which introduced a limitation in buffer sizes...
I added support for sending data in bulk via HAPI to avoid that oversize limit a while ago.
