### ISSUE TITLE
Failed to build on branch Houdini19.0-Unreal5.00

### ISSUE THREAD

**Issue by pyrochlore** [sideeffects/HoudiniEngineForUnreal#150]
Hi, 

Thanks for making this amazing tool.

I tried to build this plugin from source on branch Houdini19.0-Unreal5.00 
with UnrealEngine-5.0.0-early-access-2 downloaded from the unreal engine official repository,
but got "Could not find definition for module 'SubobjectEditor'" in Visual Studio.

I also searched for the key word 'SubobjectEditor' in unreal engine source but not found any module matches this.
Is there anything I missed?

**Comment by dpernuit** [comment]
Hi,

I just replied to you other issue, the source code we provide in the 5.0 branch is for the unreal5.0 source code.
If you're using EA2 (which is much older),we provide source/binaries on our release page.

https://github.com/sideeffects/HoudiniEngineForUnreal/releases/tag/v2.0.7

**Comment by pyrochlore** [comment]
> Hi,
> 
> I just replied to you other issue, the source code we provide in the 5.0 branch is for the unreal5.0 source code. If you're using EA2 (which is much older),we provide source/binaries on our release page.
> 
> https://github.com/sideeffects/HoudiniEngineForUnreal/releases/tag/v2.0.7

Hi @dpernuit,

Thanks for the reply.
This time I tried to build Houdini Engine of branch Houdini19.0-Unreal5.00 with Unreal Engine ue5-main branch.

Looks like the Unreal Engine ue5-main branch is under heavy development, I can not even build it for the latest head of  e63b3f3e86f7c33e2d87fcb2e99635f896631590 on 2/6. Thus I picked an older version 746ba571d7c4d2d443828e2500a29da4f7f50f37 on 2/5 and got a full unreal engine 5 custom build. 

With that UE build, I tried to build Houdini Engine of branch Houdini19.0-Unreal5.00.
Then I got errors different from the previous one, these errors are very likely caused by the mismatching of API.

Could you show me the exact one (the UE revision) the development team using to develop Houdini19.0-Unreal5.00 branch?

**Comment by pyrochlore** [comment]
I saw you mentioned the revision in another thread https://github.com/sideeffects/HoudiniEngineForUnreal/issues/153#issuecomment-1030400309. Will give it a try. Thanks.

**Comment by pyrochlore** [comment]
Current Houdini19.0-Unreal5.00 branch was built successfully with UE revision [a5310b515eb7e6baef31cc8188edb0bff352b4e6](https://github.com/EpicGames/UnrealEngine/tree/a5310b515eb7e6baef31cc8188edb0bff352b4e6).
Thanks a lot.
