### ISSUE TITLE
Houdini 19 to Unreal 5.00 last release is not working

### ISSUE THREAD

**Issue by Pnlvfx** [sideeffects/HoudiniEngineForUnreal#153]
I've tried like 50 method but today,after 1 week of trying I'm can't open Unreal Engine with houdini engine.
I've also downloaded source code, and built it with visual studio but I continue receiving module error

**Comment by dpernuit** [comment]
Hi,

There's not much we can do if you don't give us a little more details...
What specific errors are you getting ?
What version of UE5 are you using ?  with what version of the plugin ?

The code we provide for Houdini19.0-5.00 branch is built for UE5 source code from the unreal5.0 branch.
(early December 2021)
If you're using more recent/older source, then unfortunately, there might be some compile errors.

There's not much we can do until the official release, as currently, every studio is using a different cut of the UE5 source.

You can always use the Early Access 2 code, we dont have a branch for that, but the release page of the plugins hjas source and binaries for EA2.

https://github.com/sideeffects/HoudiniEngineForUnreal/releases/tag/v2.0.7

**Comment by Pnlvfx** [comment]
ok, perfect that's the problem, lol. I think the version is not compatible.
 I've downloaded last unreal 5.00 release yesterday on their git and I've downloaded houdini engine v.2 2.0.7 that was released 20 days ago.
So now I think that the problem is this and I think you can't do much, but if you can give me the gitcode of the version that is compatible with the last version of the Houdini Engine I can use that. I don't like a lot the EA
Ah, I have houdini 19.0.498

**Comment by Pnlvfx** [comment]
The error that I receive is:
Plugin 'Houdini Engine' failed to load because module 'HoudiniEngine' could not be found. Please ensure the plugin is properly installed otherwise consider disabling this plugin for this project.
Here I've used source code of the Houdini Engine and I've built that with runUAT.bat
but the engine doesn't start
I've also tried to use the plugin in a single project but appears another error that says that says:
'the following modules are missing or built with a different engine version:
HoudiniEngine
HoudiniEngineEditor
HoudiniEngineRuntime

**Comment by dpernuit** [comment]
Hi,

Yeah, this means that you need to build the sources of the plugin, it seems that UE can only find the source code, not the compiled libraries, so is complaining about the missing modules.
Maybe try deleting the binaries/intermediate folders ?

Also, this is the exact ue5 revision that we're currently using on our end.

https://github.com/EpicGames/UnrealEngine/tree/a5310b515eb7e6baef31cc8188edb0bff352b4e6

**Comment by NicTanghe** [comment]
![8iQs6DBnmI](https://user-images.githubusercontent.com/13624265/159681093-fd8793ea-f167-4585-aa04-d029b84355db.png)

Same problem with the latest release on previeuw 2.

**Comment by dpernuit** [comment]
Unless you're building from source, you should use the plugin binaries as a project plugin, not an engine plugin. 
I've mentioned this in the release note, this seems to be a limitation with UE5's preview builds.
