### ISSUE TITLE
Remove the PendingKill Concept

### ISSUE THREAD

**Issue by klamme** [sideeffects/HoudiniEngineForUnreal#154]
The programmers at the studio I work at are requesting that the PendingKill() concept be removed from the HEngine plugin for UE5.  Supposedly UE5 doesn't use this anymore.  Let me know if youd like more info!  Thanks! :-)

**Comment by dpernuit** [comment]
Hi Kenny,
Are you using the 5.00 branch of the plugin ? we've already removed all calls to IsPendingKill() a while ago.

**Comment by klamme** [comment]
Oh nice!  No we were still on the EA2 release of HEngine.  Ill let the programmers know then that its been updated already and get us upgraded.  Thanks for the speedy response!
