### ISSUE TITLE
HoudiniInputTranslator.cpp(3114) FVEctor3->FVector3f

### ISSUE THREAD

**Issue by klamme** [sideeffects/HoudiniEngineForUnreal#155]
Im not really sure what this means completely, but looks like in UE5 the FVector3 is declared differently.  This is all the info I got from the programming team at the studio I work at.  Let me know if more info is needed.  Thanks! :-)

**Comment by dpernuit** [comment]
Hi Kenny,

Same as my other reply, are you using the 5.00 branch?1
We've already replaced those appropriately in the 5.00 plugin...

see:

https://github.com/sideeffects/HoudiniEngineForUnreal/blob/Houdini19.0-Unreal5.00/Source/HoudiniEngine/Private/HoudiniInputTranslator.cpp#L3111

**Comment by klamme** [comment]
Oh nice!  No we were still on the EA2 release of HEngine.  Ill let the programmers know then that its been updated already and get us upgraded.  Thanks for the speedy response!
