### ISSUE TITLE
Deal with cases where Epic is using Double explicitly - UE5

### ISSUE THREAD

**Issue by klamme** [sideeffects/HoudiniEngineForUnreal#156]
I guess UE5 is using doubles explicitly in some cases.  the Programmers were wondering if this was going to be taken care of in the final release of the UE5 HEngine Plugin for Unreal.  Let me know if you need more info!  Thanks! :-)

**Comment by dpernuit** [comment]
Hi (again),

Any specific places where this is an issue that they have in mind ?
If UE needs double, we'll feed him doubles... but to be honest, when porting the plugin to 5.00 I don't recall any places where double were needed.

**Comment by klamme** [comment]
Ok, no prob...let me get some more info from the programmers for ya.  Im not sure either...they gave me very limited info.  Stay tuned!  thanks so much Damien!

**Comment by bematteo** [comment]
There was an implicit cast existing between `FVector` (double, defined using large world coordinates) and `FVector3f` (float).
With a recent change they removed the explicit conversion, and that caused the plugin not to build properly anymore.
https://github.com/EpicGames/UnrealEngine/commit/e7e64e1749ac2eabb7fb646512544ba28068ffcc
We temporarily fixed it locally by adding a bunch of casts where needed.

**Comment by WinRec** [comment]
> There was an implicit cast existing between `FVector` (double, defined using large world coordinates) and `FVector3f` (float). With a recent change they removed the explicit conversion, and that caused the plugin not to build properly anymore. [EpicGames/UnrealEngine@e7e64e1](https://github.com/EpicGames/UnrealEngine/commit/e7e64e1749ac2eabb7fb646512544ba28068ffcc) We temporarily fixed it locally by adding a bunch of casts where needed.

Well, that's the problem I encountered. Thanks for the info

**Comment by bematteo** [comment]
Looks like this was fixed in https://github.com/sideeffects/HoudiniEngineForUnreal/commit/b9c56dd4c3a79594b025cb2532a60f3de1c38f95 (I haven't tested).

**Comment by dpernuit** [comment]
Those errors were expected, as, at the time, the 5.00 plugin code was still made for preview 2.
As mentioned above, those issues have been fixed by https://github.com/sideeffects/HoudiniEngineForUnreal/commit/b9c56dd4c3a79594b025cb2532a60f3de1c38f95 when we added official UE5.0 release support to the plugin.

**Comment by brugr9** [comment]
@klamme @dpernuit @bematteo BTW: LWC in UE 5.0:
> **Large World Coordinates** are now implemented across Unreal Engine. To understand its implementation in the main engine, reference this [Large World Coordinates](https://docs.unrealengine.com/5.0/en-US/large-world-coordinates-in-unreal-engine-5) page. In brief, the data type **FVector is now `double` instead of `float`**.

(cp. *Large World Coordinates in Niagara*, URL: [https://docs.unrealengine.com/5.0/en-US/large-world-coordinates-in-niagara-for-unreal-engine/](https://docs.unrealengine.com/5.0/en-US/large-world-coordinates-in-niagara-for-unreal-engine/). In: Unreal Documentation)

See also:

* https://docs.unrealengine.com/5.0/en-US/large-world-coordinates-in-unreal-engine-5/
* https://docs.unrealengine.com/5.0/en-US/large-world-coordinates-rendering-in-unreal-engine-5/
