### ISSUE TITLE
Houdini Engine Session Lost.

### ISSUE THREAD

**Issue by Zalakanear** [sideeffects/HoudiniEngineForUnreal#158]
I have an issue with Houdini Engine 19.0.521 in Unreal 5.0 EA2. I'm running a simple HDA to import a heightfield,but after it goes through configuring and cooking,it says houdini session lost. Unreal output log shows this,

LogHoudiniEngine: Error: Houdini Engine Session lost! This could be caused by a crash in HARS.
LogHoudiniEngine: Error: Hapi failed:

Anyway to fix this ?

**Comment by dpernuit** [comment]
Try today's daily build, we had an issue that caused the session to silently fail when sending HF/Landscape data when their size exceed ~3600x3600. I submitted a fix for it yesterday.

**Comment by Zalakanear** [comment]
i'm using the latest one, which is this right ? "Houdini Engine 19.0.521" but the issue is still there, do i have to update to houdini daily build as well ?

**Comment by Zalakanear** [comment]
Any fix for this yet ?

**Comment by Zalakanear** [comment]
> Try today's daily build, we had an issue that caused the session to silently fail when sending HF/Landscape data when their size exceed ~3600x3600. I submitted a fix for it yesterday.

Any fix for this yet ?
