### ISSUE TITLE
Unreal crashes when adding a Houdini Asset component to a blueprint in UE5_EA2 and houdini 19.455.

### ISSUE THREAD

**Issue by NMB-Thomas** [sideeffects/HoudiniEngineForUnreal#160]
Unreal crashes and shows this error:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000142

UnrealEditor_Engine
UnrealEditor_HoudiniEngine
UnrealEditor_Core
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

I'm currently looking into using Houdini for a project and seeing an awful lot of crashes what is the most stable version of houdini/ue5 to be working on right now?

**Comment by dpernuit** [comment]
This issue has been fixed a while ago.
