### ISSUE TITLE
HDA at UE runtime 

### ISSUE THREAD

**Issue by alelordelo** [sideeffects/HoudiniEngineForUnreal#162]
Is it possible to run an HDA in a shipped UE app?

Ex: I have a Houdini HDA to create hairstyles. Then I expose the HDA parameters via blueprint and let user control those parameters in a shipped Unreal app.

thanks
Alex

**Comment by dpernuit** [comment]
Hi,

That is not possible for now and is a limitation of Houdini Engine being editor only.

HE at runtime would require every user to have a Houdini license, as well as every platform would need a form of valid Houdini binaries for this to work...
