### ISSUE TITLE
An error occurred during the installation of the Houdini Engine.

### ISSUE THREAD

**Issue by TF-siri** [sideeffects/HoudiniEngineForUnreal#163]
![image](https://user-images.githubusercontent.com/100553275/155929671-9301a0ef-5eff-49b5-9395-ab4364d52555.png)

I tried to install the HoudiniEngine for UE5 EA, but it did not work.

Is it possible to create a "Plugins" folder in the UE5 EA project folder and copy it there?

Also, when I unzip this plug-in, the name is "HoudiniEngineForUnreal-Houdini19.0-Unreal5.00", and the - and . I'm sure I couldn't use - or . in the name of the plugin, is that okay? If I rename the folder for this to HoudiniEngine, I get the same error.

Also, do I need VisualStudio for this plugin?

Finally, when will the UE5-Preview1 version of HoudiniEngine be released?

I know I'm asking a lot of questions, but I'd appreciate it if you could help me out.

**Comment by DsharpK** [comment]
Did you copy the contents of the binary file correctly as well?
*Into HoudiniEngine￦Binaries￦Win64
**You will also need to move these files and the contents of Notepad to the binary folder of the client.

**Comment by TF-siri** [comment]
> Did you copy the contents of the binary file correctly as well? *Into HoudiniEngine￦Binaries￦Win64 **You will also need to move these files and the contents of Notepad to the binary folder of the client.

Thanks for the reply.

I'm not very familiar with UnrealEngine, so this is a rudimentary question, but do you know where I can find the binary files for Houdini 19?

**Comment by dpernuit** [comment]
This error means that the binaries you're using are built for a different version of Unreal than the one you're currently using.

Binaries files are available on this repo's release page, or ship with your Houdini install, in the engine\unreal folder.
