### ISSUE TITLE
Whether data can be transmitted without HDA

### ISSUE THREAD

**Issue by gaoyan2659365465** [sideeffects/HoudiniEngineForUnreal#165]
I feel that HDA is very slow, and it seems unnecessary to use HDA if you just use Houdini to create points and go into UE5 to generate scenarios based on UE5 models.
For example, use socket TCP connection to directly transmit Houdini data to UE5 blueprint, and then use blueprint to process these data and generate scenarios. I think this is relatively fast.
For now, you have to have an HDA and then pour it into UE5.

**Comment by dpernuit** [comment]
Houdini Engine's main purpose is to allow the use of HDAs in other programs... 
but you're right, in some case, an HDA might be overkill for a simple task.
