### ISSUE TITLE
Binary release for UE5

### ISSUE THREAD

**Issue by ligaofeng0901** [sideeffects/HoudiniEngineForUnreal#177]
In this page https://www.sidefx.com/community/unreal-engine-5/. It indicates that the plugin can work together with UE5(not the EA or preview) since version 19.0.581. My houdini version is 19.0.383, does that mean that  I must upgrade the software if I wanna use it in UE5? and where can I get a binary release of the plugin for UE5.0.0 and UE5.0.1?

**Comment by dpernuit** [comment]
Yes, when a new version of Unreal is released, you will need to update Houdini and the plugin to get support.
Binary releases can either be found on this repo, and also come with the houdini install, in the engine/unreal folder.
