### ISSUE TITLE
Houdini Asset doesn't render temporary static mesh in Play In Editor mode when using World Partition in UE5.0  

### ISSUE THREAD

**Issue by ghost** [sideeffects/HoudiniEngineForUnreal#180]
Houdini Asset doesn't render temporary static mesh in Play In Editor mode when using World Partition Levels in UE5.0.1 
It works as expected in streaming levels

To see mesh in Play In Editor it's necessary to bake assets into actors

**Comment by dpernuit** [comment]
That issue has been fixed
