### ISSUE TITLE
Unreal Engine 4.11 port.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#19]
- [x] Branch 4.10 code into 4.11 .
- [x] Create GitHub branch.
- [x] Deprecate 4.9 branch.
- [x] Fix API differences and fix deprecations in 4.11 .
- [x] Internal build system integration.
- [x] Houdini Installer integration.
- [x] Change of hashing for Houdini Geo Object Part (name based).
- [x] Change of _unreal_face_material_ attribute to _unreal_material_ attribute.
  - [x] Adding fallback to _unreal_face_material_ for compatibility reasons.
- [x] Look into building Game modules for Win and Mac OS X (right now we are building Editor modules only).
- [x] Set default scale in preferences to 100 (instead of current 50).
- [x] Update plugin category. At the moment it is Rendering.Components . Move to a category of its own?
- [x] Update Engine and MinEngineVersion versions in .uplugin file.
- [x] GeoPartObject refactoring.
  - [x] GeoPartObject serialization versioning.

---

Filed as RFE # 73549 : HAPI: Unreal: UE4 4.11 port.

**Comment by robeastham** [comment]
I've manged to build this from source with the current UE4 branch for 4.11 and after quite a number of false starts it now appears to be functioning correctly. 

Should I be using it yet or are there some gotchas I'm likely to run into?

**Comment by ttvd** [comment]
Hello!

No, I believe it should be on par with the other branches. We need to do some internal work to integrate it with our build tools, but this should not affect you in any way. We also will be deprecating 4.9 in the few upcoming days. 

Thank you!

**Comment by robeastham** [comment]
Any update on this? Still looks like a way to go?

Keen to use with 4.11.1 if possible, ideally don;t want to compile from source again and just use vanilla 4.11.1 downloaded from Epic.

**Comment by Yelmond** [comment]
4.11 support should now be in the Windows installers. Mac is taking a bit longer.

**Comment by robeastham** [comment]
Thanks! Can confirm that I have it working with 4.11.2 on Windows now :-)

**Comment by Yelmond** [comment]
Mac should have 4.11 as well now. 4.12 too.
