### ISSUE TITLE
InstancedFoliageActor->AddMesh(),Epric said partioned world can't use this api any more,so...

### ISSUE THREAD

**Issue by cgTD123** [sideeffects/HoudiniEngineForUnreal#191]
FFoliageInfo* AInstancedFoliageActor::AddMesh
// This function is deprecated in a partioned world.
// FoliageType cannot have an AInstancedFoliageActor as their Outer
// This creates issues with the Foliage Edit mode.
// Proper way is to Create an asset for the UFoliageType and call
// the InstancedFoliageActor::AddMesh(UFoliageType*) overload with the asset

**Comment by dpernuit** [comment]
The plugin doesn't currently support WP.
