### ISSUE TITLE
Baking Static mesh doesn't generate anything because IsObjectTemporary(UObject*, const EHoudiniOutputType&) doesn't seem to work as intended

### ISSUE THREAD

**Issue by dustars** [sideeffects/HoudiniEngineForUnreal#195]
Hi,

I've been trying to bake static mesh in UE 5.1 by assigning unreal_bake_folder, but nothing is generated except files in temp folder. After debugging, I found out line "IsObjectTemporary(InObject, InOutputType)" always returns false, so I changed the last return statement in this method to "return true" and now things work again!

I'm not sure if this is intended or a bug, so I decided to open this issue to bring it up. I'd be appreciated if more info could be given.

Thanks!

**Comment by dpernuit** [comment]
Hi,

Thanks for bringing this up!
You're right, this is wrong, and the function should indeed return true at the end... 
That issue was likely introduced when backporting the change when we added the "Baked"  meta.
The change will be in tomorrow's daily build.
