### ISSUE TITLE
Missing assets for tests

### ISSUE THREAD

**Issue by p4vv37** [sideeffects/HoudiniEngineForUnreal#202]
Hi

I'm trying to modify the plugin a bit and I'd like to run tests to verify my changes. Apparently some .usasset files are missing from this repository:

`Created a new scene because it didn't exist! Please commit to dev_reg: /Game/TestSaved/Levels/Colliders and /Game/TestSaved/Assets/Colliders/Colliders_Common [[...]\Engine\Plugins\Runtime\HoudiniEngine\Source\HoudiniEngineEditor\Private\Tests\HoudiniEditorTestUtils.cpp(590)]`

Is that correct and assets are missing, or am I doing something wrong?

Regards

**Comment by dpernuit** [comment]
No that is expected, those tests are mostly meant to be run internally on our build machines.
