### ISSUE TITLE
Crash with UE 5.1 generating Landscapes

### ISSUE THREAD

**Issue by Kaiserlicht** [sideeffects/HoudiniEngineForUnreal#209]
I gave 5.1 a first spin today. I managed to compile the plugin. Most of the HDA's I tested work fine. But a very simple one which loads a Heightfield from bgeo crashed Unreal after importing the resulting Landscape. The same HDA works fine with 5.0.3

```
Assertion failed: !bPostTickComponentUpdate [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\LevelTick.cpp] [Line: 911]

UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Landscape
UnrealEditor_Engine
UnrealEditor_HoudiniEngineRuntime!UHoudiniAssetComponent::UpdateRenderingInformation() [E:\Unreal\Fondo\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniAssetComponent.cpp:2946]
UnrealEditor_HoudiniEngineRuntime!UHoudiniAssetComponent::CreateRenderState_Concurrent() [E:\Unreal\Fondo\Plugins\HoudiniEngine\Source\HoudiniEngineRuntime\Private\HoudiniAssetComponent.cpp:1560]
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

**Comment by Kaiserlicht** [comment]
[hf_test.zip](https://github.com/sideeffects/HoudiniEngineForUnreal/files/10055397/hf_test.zip)
Here is a super simple hda to reproduce. Just a default landscape, nothing else. UE 5.1 crashes on import...

**Comment by dpernuit** [comment]
Hi,
What version of the plugin  / Houdini are you using ? Do you happen to be using World Partition?
You should try with a recent daily build, we've been fixing a lot of WP issues lately.

**Comment by Kaiserlicht** [comment]
We're using the latest version that was released, so Version 2.0.14 - Houdini 19.5.435.
We're not using world partition. Does it work on your side?

**Comment by Sadowick** [comment]
Same error with single and tiled landscapes, tried with many sizes. It worked in 5.03. Using world partition (the default open world initial project)

**Comment by JasonCaron** [comment]
same error here as well,

**Comment by panduoraz** [comment]
same error ，ue5.1 market version ， when you import heightfeild to ue landscape, ue5.1  crashed,date :2022/12/7

**Comment by Jamesdavidstone** [comment]
This is still happening

**Comment by linuxbug** [comment]
LoginId:e2c00488cb994f1e80f95d1dcc466735-000003e8
EpicAccountId:

Assertion failed: !bPostTickComponentUpdate [File:./Runtime/Engine/Private/LevelTick.cpp] [Line: 911]

libUnrealEditor-Engine.so!UWorld::MarkActorComponentForNeededEndOfFrameUpdate(UActorComponent*, bool) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/LevelTick.cpp:911]
libUnrealEditor-Engine.so!UActorComponent::MarkRenderStateDirty() [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/Components/ActorComponent.cpp:1841]
libUnrealEditor-Landscape.so!ULandscapeHeightfieldCollisionComponent::OnCreatePhysicsState() [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Landscape/Private/LandscapeCollision.cpp:282]
libUnrealEditor-Engine.so!UActorComponent::CreatePhysicsState(bool) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/Components/ActorComponent.cpp:1631]
libUnrealEditor-HoudiniEngineRuntime.so!UHoudiniAssetComponent::UpdateRenderingInformation() [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./../Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniAssetComponent.cpp:2977]
libUnrealEditor-HoudiniEngineRuntime.so!UHoudiniAssetComponent::CreateRenderState_Concurrent(FRegisterComponentContext*) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./../Plugins/Runtime/HoudiniEngine/Source/HoudiniEngineRuntime/Private/HoudiniAssetComponent.cpp:1580]
libUnrealEditor-Engine.so!UActorComponent::RecreateRenderState_Concurrent() [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/Components/ActorComponent.cpp:1736]
libUnrealEditor-Engine.so!UActorComponent::DoDeferredRenderUpdates_Concurrent() [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/Components/ActorComponent.cpp:1809]
libUnrealEditor-Engine.so!UWorld::SendAllEndOfFrameUpdates()::$_80::operator()() const [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/LevelTick.cpp:1167]
libUnrealEditor-Engine.so!UWorld::SendAllEndOfFrameUpdates() [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/LevelTick.cpp:1184]
libUnrealEditor-Engine.so!UReflectionCaptureComponent::UpdateReflectionCaptureContents(UWorld*, char16_t const*, bool, bool, bool) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Engine/Private/Components/ReflectionCaptureComponent.cpp:1069]
libUnrealEditor-UnrealEd.so!UEditorEngine::Tick(float, bool) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Editor/UnrealEd/Private/EditorEngine.cpp:1797]
libUnrealEditor-UnrealEd.so!UUnrealEdEngine::Tick(float, bool) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Editor/UnrealEd/Private/UnrealEdEngine.cpp:514]
UnrealEditor!FEngineLoop::Tick() [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Launch/Private/LaunchEngineLoop.cpp:5361]
UnrealEditor!GuardedMain(char16_t const*) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/./Runtime/Launch/Private/Launch.cpp:204]
libUnrealEditor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/home/linuxbug/soft/UnrealEngine-5.1.0-release/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:269]
libc.so.6!__libc_start_main(+0xf2)
UnrealEditor!_start()

**Comment by Fierykev** [comment]
Tested today on the Daily Build.  Still occurring.  12/12

**Comment by Kaiserlicht** [comment]
Works for me with 19.5.468. Thank You
