### ISSUE TITLE
Over-Cooking World outliner input to frequently

### ISSUE THREAD

**Issue by Avgilles** [sideeffects/HoudiniEngineForUnreal#212]
Hello, 
When I enable the *"world outliner input"* it reloads every frame to cook. Then it is very difficult to use Unreal.
My Unreal version :
5.0.3
Houdini engine version :
19.0.720

I tried on unreal engine 4.27 and there are no bugs.
Thanks
[Not good in 5.0.3](https://share.descript.com/view/20LNm2dh8bG)
[good in UE 4.27](https://imgur.com/gallery/K3ratn6)

**Comment by dpernuit** [comment]
This issue has been fixed a few months ago in H19.0.735

See
https://github.com/sideeffects/HoudiniEngineForUnreal/commit/d25f0e342430893a0dbbf6e00f111910a08af148
