### ISSUE TITLE
Houdiniimport.uasset fails to compile on 5.1

### ISSUE THREAD

**Issue by Edstub207** [sideeffects/HoudiniEngineForUnreal#217]
We've fixed this locally on our project, but both instances of HoudiniImport have outdated versions of the Send to Unreal node for the Package Name and Package Folder.

**Comment by Edstub207** [comment]
Hey @andys-sidefx any chance of this PR being merged? A few have been hit by this and we hit it every time we merge.

**Comment by dpernuit** [comment]
Those assets weren't needed/used by the plugin anymore/and just simply needed to be deleted.
