### ISSUE TITLE
Landscape Spline Support

### ISSUE THREAD

**Issue by reubenthekaiju** [sideeffects/HoudiniEngineForUnreal#222]
Hi,

My team is interested in using Unreal's landscape splines to generate roads. You can already do this using Unreal tools ([see this video for an example](https://youtu.be/8WIWuybAKj4?t=402)), but it's pretty basic and we want to leverage Houdini to give us extra power for this tool.

Based on using the tool and reading the code, it doesn't seem like any support for landscape splines has been implemented yet. We are planning on adding this capability to the HoudiniEngineForUnreal plugin ourselves. However, ideally it could be done in a way that could be merged back into the mainline, so we don't have to do a merge every time we take an update. Would that be possible?

I believe there are two approaches:
1. Add a new `EHoudiniInputType::LandscapeCurve`, which translates Unreal landscape splines to Houdini curves.
2. Add spline support to the existing `EHoudiniInputType::Landscape`, by adding a set of child input curve nodes that map to the splines that are part of the selected `ALandscapeProxy`, and are parented to the parent landscape.

So far we are going with approach 1 since it seems more straightforward and gives us the potential to have a better UX around controlling which splines to marshal to Houdini, but since we are interested in getting a PR accepted, we could switch to 2 or a different approach if you prefer. 

We'd appreciate any insight, thanks!

**Comment by dpernuit** [comment]
Hi,
Closing this - as support for landscape spline has been added in H20
