### ISSUE TITLE
Pack node is no longer working when baking

### ISSUE THREAD

**Issue by pixelprato** [sideeffects/HoudiniEngineForUnreal#227]
We're using Pack node to split meshes by an attribute:

**Problem:** 
When baking, the "many" meshes desired are exported with the same one at the same place.

**Simple Case:**
Let say you have 2 triangles, want to export them as 2 separated meshes.
You set an attribute to int **0** to one and the other to int **1** simply.
Pack can package or split meshes by a dedicated attribute, when this attrib varied.

-  435 & 493 are doing properly in "temp", when meshes are generated within the HDA uasset in world

-  435 is baking properly, 2 separated meshes in the content browser

- 493 is baking wrong, duplicating the first item over and over

**Comment by faxlab** [comment]
Second this its completely broken and its a waste of my time, I've spent days trying to figure out what I was doing wrong when it turns out the plugin was released in a half-working state. Please fix

**Comment by faxlab** [comment]
@pixelprato did you ever solve this?

**Comment by dpernuit** [comment]
Hi,
This issue's been fixed in H19.5.526 build of the plugin, and so is fixed in the latest prod build/release.
