### ISSUE TITLE
Dragging multiple static meshes into an instanced input.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#23]
At the moment we support dragging a single static mesh into an instanced input in order to instance it. We also support splitting instance inputs into multiple (via instanced variation). It would be useful to be able to drag multiple static meshes into an input and have it split automatically into multiple, depending on the number of dragged in static meshes.

---

Filed as RFE: #73662 : Unreal: Add support for dragging multiple static meshes into instance input.

**Comment by ttvd** [comment]
Referenced in 
https://www.sidefx.com/index.php?option=com_forum&Itemid=172&page=viewtopic&p=193879#193879

**Comment by cgrebeld** [comment]
Not unless someone asks.
