### ISSUE TITLE
May I ask if the latest version of Houdini 19.5.534 no longer has a compatible version of Houdini Engine for Unreal 4.26?

### ISSUE THREAD

**Issue by aTofua** [sideeffects/HoudiniEngineForUnreal#238]
May I ask if the latest version of Houdini 19.5.534 no longer has a compatible version of Houdini Engine for Unreal 4.26?

**Comment by dpernuit** [comment]
Hi,

We still backport most of the changes to 4.26, so the source code is up to date.
However,  we don't ship the 4.26 plugin anymore on windows, so you'll need to build the plugin from source on the Houdini19.5-4.26 branch.
We normally only support the latest 2 versions of UE, but will try to maintain 4.27 / 26 for a little longer.
