### ISSUE TITLE
please update 5.2

### ISSUE THREAD

**Issue by samrat333** [sideeffects/HoudiniEngineForUnreal#241]
we trayed to build many time 5.2 but not success but build fine lower version please help

**Comment by samrat333** [comment]
please update source file for ue 5.2

**Comment by RobJinn** [comment]
+1 
Please, can you update a compiled version for the preview 2

**Comment by errorsandwarnings** [comment]
+2, I really need the compiled version for the preview 2.

**Comment by marciocamello** [comment]
+3,Me too :D

**Comment by JasonMa0012** [comment]
+4, please

**Comment by skomdra** [comment]
+5 me too :) now the 5.2 is officially released

**Comment by dpernuit** [comment]
Hi,

Support for UE5.2 was added a few weeks ago - last 5.2 fix was in H19.5.586 / April 14th.
Just tried with the official 5.2, and it doesn't seem there is any significant issue with the official release over preview 2.

Same than with UE5.1, we wont be creating a separate branch for 5.2, as all UE5 version of the plugin use the same code base.

Official support for 5.2 (binaries of the plugin in the Houdini installer) will be added in a couple days.
