### ISSUE TITLE
Plugin won't build with 5.2

### ISSUE THREAD

**Issue by ao-cmi** [sideeffects/HoudiniEngineForUnreal#248]
Hi,

I've tried a lot of different ways to build this plugin for 5.2 and for some reason it keeps failing. Thanks for the help!

**Comment by JElbourne** [comment]
Fixed this one for our own use. 

https://github.com/sideeffects/HoudiniEngineForUnreal/pull/250

You can grab for your own needs. Has not been merged in or approved by Sidefx at this time

**Comment by talal-jpg** [comment]
sorry for such a question but how to download the fixed version for engine and is it working on linux too?

**Comment by dpernuit** [comment]
The latest daily build should build fine as we've rolled out the latest fixes for non-unity / no-pch builds.
You can get the source either from the repo, or with the daily build installer.

**Comment by ao-cmi** [comment]
Awesome! Thank you!

**Comment by iHad168** [comment]
HI
I UE5.2 cannot ask me to build plugin
```
LogInit: Warning: Incompatible or missing module: HoudiniEngine
LogInit: Warning: Incompatible or missing module: HoudiniEngineEditor
LogInit: Warning: Incompatible or missing module: HoudiniEngineRuntime
LogLinux: Warning: MessageBox: The following modules are missing or built with a different engine version:

  HoudiniEngine
  HoudiniEngineEditor
  HoudiniEngineRuntime

Would you like to rebuild them now?: Missing ProceduralCastle Modules: No is implied.
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogVirtualization: UE::Virtualization was shutdown
```
I need use what command option to Build?
