### ISSUE TITLE
Curve baking.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#25]
It would be nice to be able to bake Houdini generated curves into UE4 native curves (Blueprint with SplineComponent attached).

---

Filed as RFE #73666 : Unreal: Curve baking.

**Comment by ttvd** [comment]
Related SideFX forum thread: https://www.sidefx.com/index.php?option=com_forum&Itemid=172&page=viewtopic&p=193891#193891

**Comment by pavelkrupala** [comment]
+1 this will be really usefull feature!

**Comment by melMass** [comment]
Much needed indeed, I read it will be part of v2 (delayed to March...)

**Comment by dpernuit** [comment]
Confirming we do intend on having this in v2.

**Comment by dpernuit** [comment]
closing, as curve output was added in v2
