### ISSUE TITLE
Mismatching HAPI version in Houdini Engine and Houdini 19.5.633

### ISSUE THREAD

**Issue by doppioslash-wushu** [sideeffects/HoudiniEngineForUnreal#254]
The HAPI version in Houdini, and the one hardcoded in `Source/HoudiniEngine/Public/HAPI/HAPI_Version.h` have stopped matching.

Houdini 19.5.**633** has HAPI version 5.0.**7**, while the Houdini Engine for 19.5.633 (commit a6def132327b48f6bdd225821daebd1af8c199eb) still expects version 5.0.**6**.
I tested a few versions, Houdini has been using HAPI 5.0.7 at least since 19.5.605.

It looks like the regression to 5.0.6 in the Houdini Engine code has been introduced in this commit: 77237a3f73f9f821e9a68662eadef424265a10c3.

![image](https://github.com/sideeffects/HoudiniEngineForUnreal/assets/97295909/182ef1ef-4cd3-4042-a8ef-b50fd66eb453)

**Comment by dpernuit** [comment]
Hi,
Thanks for bringing this up, those files are normally auto-generated, but it seems that we manually introduced that regression by accident!
It should be fixed in tomorrow's daily build of the plugin.

**Comment by doppioslash-wushu** [comment]
Thanks, but it looks like the version has been set back to 5.0.6 again @dpernuit 

![image](https://github.com/sideeffects/HoudiniEngineForUnreal/assets/97295909/9eb45c00-076c-4cf3-a851-fdc4ec9ae301)

![image](https://github.com/sideeffects/HoudiniEngineForUnreal/assets/97295909/8576a1f4-a162-43f2-8d6f-da91d473f251)
