### ISSUE TITLE
UE5.2 Crashing when a static mesh is assigned to an HDA input

### ISSUE THREAD

**Issue by doppioslash-wushu** [sideeffects/HoudiniEngineForUnreal#255]
A simple HDA which accepts a static mesh as input crashes UE.

It happens when using:
- UE5.2 (source build from `5.2.0-release`) 
- HE (from d5b3b77e449cc00697a902399feee7291c02a4df) 
- Houdini 19.5.633

Unreal crashes as soon as a static mesh is assigned to the input.
The cause is a null pointer at `UnrealMeshTranslator.cpp`, line 3260.

The example HDA (attached, but it's nothing fancy):
![image](https://github.com/sideeffects/HoudiniEngineForUnreal/assets/97295909/c9601d74-1621-4330-afef-e1e1c5fede99)
[sop_he_ue_5.2_test.zip](https://github.com/sideeffects/HoudiniEngineForUnreal/files/11655055/sop_he_ue_5.2_test.zip)

It crashes as soon as a static mesh is assigned to the input in UE:
![image](https://github.com/sideeffects/HoudiniEngineForUnreal/assets/97295909/c474b310-cde7-4a1c-8621-1e2c9652760b)

**Comment by peternicolai** [comment]
FWIW, I got the same result. UE5.2.1 code from 5.2 release branch, HEngine from 19.5.637.

**Comment by dpernuit** [comment]
Hi,
Thanks for bringing this up, that regression will be fixed in tomorrow's daily build of the plugin.

**Comment by doppioslash-wushu** [comment]
Thanks @dpernuit 
We have a source build of Houdini Engine from github, so we don't use the daily build from the launcher.
Do you know when this fix will land over here in github?

**Comment by dpernuit** [comment]
Hi,

The fix's already on this git repo... it's normally updated every day ~midnight (EST) 

(but lately, it seems to randomly have issues, and sometimes needs a manual kick... )

**Comment by doppioslash-wushu** [comment]
Thanks, I can see it now. 
Yeah, none of the commits from yesterday were showing up on github as of an hour ago.

Btw the commit messages are still saying the API is 5.0.6
![image](https://github.com/sideeffects/HoudiniEngineForUnreal/assets/97295909/abc2e6eb-267e-4e86-b1f5-ad023eb6b3ef)
