### ISSUE TITLE
Baked / native curve input.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#26]
We would like to be able to use UE4 native splines (Blueprint with SplineComponent attached) or perhaps UE4 curve mesh as curve asset inputs. At the moment you have to either use asset connection that has a curve inside, or you have to make a curve yourself in curve input.

---

Filed as RFE #73667 : Unreal: Baked curve input.

**Comment by ttvd** [comment]
Referenced in https://www.sidefx.com/index.php?option=com_forum&Itemid=172&page=viewtopic&p=193891#193891

**Comment by cgrebeld** [comment]
Fixed.
