### ISSUE TITLE
Cook times doubled / tripled due to post-cook UpdateEditorProperties call

### ISSUE THREAD

**Issue by jeremyabel** [sideeffects/HoudiniEngineForUnreal#285]
I was investigating why my cook times were so slow (7 seconds for a HDA that just outputs a cube) and I noticed that a lot of time was being spent updating the details panel in the PostCook function. I commented out the call to `FHoudiniEngineUtils::UpdateEditorProperties(HAC, true);` on line 1315 in HoudiniEngineManager.cpp and my cook times went down to a much more reasonable 2 seconds. I'm not seeing any issues with the details panel after commenting this line out. Is it necessary?

UE Version: 5.3.0

EDIT: I've had that line commented out for a day now and all seems to be stable so far

**Comment by dpernuit** [comment]
Hi,
Apologies for the delay - but this issue has been fixed in recent versions of the plugin.

**Comment by jeremyabel** [comment]
Fantastic, thanks!
