### ISSUE TITLE
Version 2.0.14 - Houdini 19.5.435 not work for ue 5.3

### ISSUE THREAD

**Issue by sss1337xyz** [sideeffects/HoudiniEngineForUnreal#287]
I am facing problems that I cannot use the plugin for houdini version 19.5.435 in ue 5.3.2

when starting a project, I am asked to recompile, but even if it is done, it does not help.

https://prnt.sc/jieunzaoJ33A

I understand that support for this version of the ue has not been announced, but perhaps there is some fix that I could reproduce.

Thanks for any help

upd: I also tried to install the plugin version 2.1.0, it already appears in the project, but unfortunately no session is created

**Comment by dpernuit** [comment]
IIRC, 5.3 was released way after 19.5.432 - likely, the solution is to update your 19.5 build to a more recent daily build of H.
(or to update to H20)
But we can't retro-actively add support to newer versions of unreal to an already released production build of H.
