### ISSUE TITLE
Planned release For UE5.4 ?

### ISSUE THREAD

**Issue by Takarigata** [sideeffects/HoudiniEngineForUnreal#291]
Hello, I tried to compile the last version on this repo for UE 5.4 but it was not working which was pretty predictable ngl since they changed a tons of stuff in this version ! 
Are there any ETA or planned release for 5.4 ? 

Charlotte

**Comment by dpernuit** [comment]
Hi,
Yes, that's expected, Epic likes to break a ton of things with each new release.
We don't support unreleased versions of UE as the code is too unstable, I could fix it for today's build of 5.4, and it could break tomorrow... 
We generally support new builds of UE a few days after their official release.

**Comment by Takarigata** [comment]
Yeah I see ! I’m gonna test fixing it for now and we’ll wait for your
release.
Thanks for your reply !

2024年2月20日(火) 午後4:07 Damien Pernuit ***@***.***>:

**Comment by srwxr-xr-x** [comment]
Bumping this! I'm using the 5.4 Preview

**Comment by zazizazi** [comment]
+1

**Comment by samrat333** [comment]
+1

**Comment by samrat333** [comment]
please update  5.4

**Comment by Takarigata** [comment]
The repo has been update for 5.4 ! Thanks !

**Comment by dpernuit** [comment]
Yep, I pushed the 5.4 update to the repo - it will still be a few days before we add the 5.4 plugin binaries to the installer.

For now, use at your own risk and expect regressions - as usual, Epic broke a ton of things with 5.4 and we're fixing those issues as we find them.
