### ISSUE TITLE
Why there is release for 4.27 but not for 5.1 windows?

### ISSUE THREAD

**Issue by AzadNezamdoust** [sideeffects/HoudiniEngineForUnreal#293]
Why there is release for 4.27 but not for 5.1 windows? We are not using source version of the engine.

**Comment by dpernuit** [comment]
Maybe you're looking at older versions of Houdini ? or an older release of the plugin ?
The UE5 plugins have been available since H19.5+ 
The latest release has binaries for 5.3 5.2.
