### ISSUE TITLE
Question; landscape asset input support.

### ISSUE THREAD

**Issue by JaapSuter** [sideeffects/HoudiniEngineForUnreal#3]
I just noticed commit c6b9d1e42bc80c279397e5c12c88b4995be457c5, and I'm wondering if you may be able to expand on what's planned for the future in this regard. It may possibly overlap with some work I'm doing, and if instead of doing my own thing I can leverage Side Effect's work, that'd be great.

**Comment by ttvd** [comment]
Hello! Sorry for delayed reply - I did not get notification from Github for some reason.

We are working on Landscape input. This work has been requested for instancing things (static meshes) on the terrain. We are planning to add marshalling of height map as point data (maintaining landscape component index, and corresponding point data, such as uv, weightmap uv, normals, unreal material name etc) as well as marshalling of terrain splines as curves. Inside the asset you would need to remesh the point cloud and use it for instancing / placement. 

Another aspect is the poly paint of the terrain - currently we have no way of marshalling textures into Houdini Engine. So this workflow needs a further thought.

We are still doing research on modifying the landscape by an asset or creating landscape from inside the asset after cooking. This mostly comes down to workflow / interaction issues. 

What is your use case? Do you have a particular interaction / workflow in mind? Thanks for letting us know!

**Comment by JaapSuter** [comment]
It sounds like you guys are working on the kinds of things we have a use for. I'll close this issue for now, and open up specific ones when I have ideas or requests (or a pull request perhaps). Thanks again!
