### ISSUE TITLE
Improvements to instance baking.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#30]
At the moment we can only bake instances into a Blueprint. It would be nice to be able to bake instances into one static mesh.
# 

Filed as RFE #73707 : Unreal: Improvements to instance baking.

**Comment by ttvd** [comment]
Related to https://github.com/sideeffects/HoudiniEngineForUnreal/issues/49

**Comment by xDiavalx** [comment]
I am not sure this makes much sense. Technically one could feed the points that define the instance placements into a copy SOP and stamp the target meshes onto these points. Provided the inputs are the same, that would lead to the same result as if one had baked all instances into a mesh. (By the way, this is how this feature could be easily implemented without any complex code.)

More interesting would be the option to bake the "instances" as individual mesh placements into the "World Outliner". This would be useful if the Houdini procedure is used to make only a few mesh placements. In that case baking as mesh placements to the World Outliner would yield better performance than a blueprint with instances. I think that was the original idea behind this RFE anyways (but I might be wrong and that is another RFE). 

Note: When I say "bake the individual mesh placements" into the "World Outliner"" I mean that the process should bake each different mesh type to the Content directory (if the mesh is not already in there) and then place those meshes in the scene with the correct position scale and rotation values (as if an artist had dragged the mesh into the scene and made placements by hand). This could be achieved by using the mesh copy paste functions of Unreal. (Freek Hoekstra implemented this to great effect with a script by Jan Pijpers for Unreal 3. The same principle would still work in Unreal 4. Freek used to work for SideFX so you should be able to find out more about it that way, if necessary, or you could ask Jan directly.)

**Comment by cgrebeld** [comment]
I agree that combining instances on the plugin side seems a bit redundant since you can easily do that in your asset.
@xDiavalx Baking to the Outliner is possible using the 'Bake to Actors' button in the detail panel.
