### ISSUE TITLE
Namespace GTE redefinition

### ISSUE THREAD

**Issue by IvayloH** [sideeffects/HoudiniEngineForUnreal#300]
The conflict appears when you install the GeometryProcessing plugin, as it is using the same namespace/code. We've locally changed it to "namespace houdini::gte" to resolve it short-term but might be better to just rely on the engine plugin instead.

**Comment by dpernuit** [comment]
Hi,

Thanks for bringing this up - I've renamed the namespace on our end as well, those should prevent conflicts with the local copy of GTE. The fix will be in tomorrow's daily.

We can't rely on the engine plugin - as it is an experimental plugin - and don't want to introduce an unnecessary dependency.
If this ever gets brought in UE "proper" and can access it as a normal engine module - then we'll remove the local copy.
