### ISSUE TITLE
error: expression result unused [-Werror,-Wunused-value]

### ISSUE THREAD

**Issue by dantethemetaphor** [sideeffects/HoudiniEngineForUnreal#305]
During build on i get this error on linux and UE 5.4, commenting out the files in question allows build to proceed

------ Building 5 action(s) started ------
[1/5] Compile HoudiniEditorUnitTestUtils.cpp
/home/dante/Documents/Unreal Projects/MyProject/Plugins/HoudiniEngine/Source/HoudiniEngineEditor/Private/Tests/HoudiniEditorUnitTestUtils.cpp:170:2: error: expression result unused [-Werror,-Wunused-value]
        BakeOutputs;
        ^~~~~~~~~~~
1 error generated.
[2/5] Compile HoudiniSkeletalMeshTranslator.cpp
/home/dante/Documents/Unreal Projects/MyProject/Plugins/HoudiniEngine/Source/HoudiniEngine/Private/HoudiniSkeletalMeshTranslator.cpp:412:16: error: expression result unused [-Werror,-Wunused-value]
        ShapeMeshHGPO.PartId;
        ~~~~~~~~~~~~~ ^~~~~~
/home/dante/Documents/Unreal Projects/MyProject/Plugins/HoudiniEngine/Source/HoudiniEngine/Private/HoudiniSkeletalMeshTranslator.cpp:413:16: error: expression result unused [-Werror,-Wunused-value]
        ShapeMeshHGPO.GeoId;
        ~~~~~~~~~~~~~ ^~~~~
2 errors generated.
Total time in Parallel executor: 15.37 seconds
Total execution time: 16.55 seconds

 *  The terminal process "/usr/bin/zsh '-c', 'Engine/Build/BatchFiles/Linux/Build.sh MyProjectEditor Linux Development '/home/xxx/Documents/Unreal Projects/MyProject/MyProject.uproject' -waitmutex'" terminated with exit code: 6.

**Comment by dpernuit** [comment]
Hi,
Thanks for bringing this up - these errors have been fixed.
