### ISSUE TITLE
LibHAPILocation can be added multiple times to the PATH env var

### ISSUE THREAD

**Issue by manugulus** [sideeffects/HoudiniEngineForUnreal#308]
In FHoudiniEngine::StartSession, in the lambda UpdatePathForServer, if we start and stop a Houdini session multple times without restarting Unreal. PATH already contains the LibHAPILocation so its readded each time. PATH ends up being really huge. To repro, Stop/Start Houdini Engine session mutliple times and check the value of ModifiedPath.

**Comment by dpernuit** [comment]
Hi,
Thanks for bringing this up! I just pushed a change that will prevent the plugin from updating the PATH multiple times, it will be available in tomorrow's daily builds of the plugin.
