### ISSUE TITLE
Enabling 'transform change triggers cooks' option is broken.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#32]
Enabling 'Transform Change Triggers Cooks' option in details panel triggers infinite cooking loop.

---

Filed as BUG #73804 : Unreal: Enabling transform change triggers cooks option is broken.

**Comment by Yelmond** [comment]
Fixed in: 617794fed5dd306fadd71f5e8ccf87e631a1f235
