### ISSUE TITLE
Access from C++ (plugin API surface).

### ISSUE THREAD

**Issue by JaapSuter** [sideeffects/HoudiniEngineForUnreal#34]
Initial discussion and brainstorming is on the SideFX forum:
- [Access from C++ (plugin API surface)](https://www.sidefx.com/index.php?option=com_forum&Itemid=172&page=viewtopic&p=194347#194347)

Once decisions or designs are more fleshed out, we can move actionable items over here.

**Comment by cgrebeld** [comment]
We've made some moves towards this.  The API is whatever classes we put into
Source/HoudiniEngineRuntime/Public

The plan is to gradually refactor and add more functionality to the API going forward.
