### ISSUE TITLE
Save Current Houdini Scene (save as HIP).

### ISSUE THREAD

**Issue by JaapSuter** [sideeffects/HoudiniEngineForUnreal#35]
While browsing the forums for the Unity plugin,  I encountered the following in [this thread](https://www.sidefx.com/index.php?option=com_forum&Itemid=172&page=viewtopic&p=146532): 

That said, always make sure your asset works as intended in Houdini before bringing it to Unity. The best way to make sure everything is consistent across the two is to load your asset in Unity and then go to the Houdini Engine menu and open the Debug Window. In it, click on "**Save Current Houdini Scene...**". Then open that scene in Houdini and make sure everything works. If things work in Houdini but not in Unity it's likely a bug so let us know, preferably also providing a reproducible minimal example asset.

That strikes me as a very useful feature. Any chance we can get something similar for Unreal?

Or have I overlooked this already being available?

Thanks,

Jaap Suter

**Comment by ttvd** [comment]
Hello Jaap!

Yes, that feature is in Unreal plugin. Go to File menu, then Houdini Engine section, then Save to HIP file.
I think renaming the menu item to something more descriptive is a good idea.

**Comment by JaapSuter** [comment]
Well that's embarrassing. I guess I had incorrectly assumed that whatever shows up on an instantiated Houdini asset is the entirety of what the plugin exposes. Meanwhile, you guys already did it, and it's actually where it should be. Doubly embarrassing, because I could've figured this out myself in 5 seconds by simply searching for "save" in the plugin codebase.

Apologies, thanks! (closing this issue).
