### ISSUE TITLE
Missing WITH_EDITOR guard for material functions.

### ISSUE THREAD

**Issue by JaapSuter** [sideeffects/HoudiniEngineForUnreal#37]
Should these functions near lines 269 to 298 in HoudiniEngineUtils.h be wrapped in a WITH_EDITOR (and correspondingly so in the .cpp file)

```
    CreateMaterialComponentDiffuse
    CreateMaterialComponentNormal
    CreateMaterialComponentSpecular
    CreateMaterialComponentRoughness
    CreateMaterialComponentMetallic
    CreateMaterialComponentEmissive
    CreateMaterialComponentOpacity
```

Otherwise I'll get a build error in my non-editor builds because `FHoudiniEngineUtils::CreateUnrealTexture` isn't available.

Thanks!

**Comment by ttvd** [comment]
Good catch! Will commit a fix ASAP.

**Comment by ttvd** [comment]
This bug should be fixed in:

H15.0/390 (Feb 18, 2016).

**Comment by ttvd** [comment]
[h15_246083.diff.txt](https://github.com/sideeffects/HoudiniEngineForUnreal/files/135014/h15_246083.diff.txt)

(diff file for H15 branches if you need it in the meantime)

**Comment by JaapSuter** [comment]
Faster than light, thanks!
