### ISSUE TITLE
Switching input types in details panel is broken if cooking on parameter change is disabled.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#39]
Switching input types (geometry, curve, asset, landscape) is broken when cooking on parameter change option is disabled in details panel. If you recook, input seems to be refreshed and works.
# 

Filed as BUG #73934 : Unreal: Switching input types in details panel is broken if cooking is disabled.

**Comment by cgrebeld** [comment]
Fixed.
