### ISSUE TITLE
Support for multiple assets within the same HDA.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#4]
At the moment we load first asset within the HDA. It would be useful to give user the ability to pick which asset they want to load, similarly to how Maya Houdini Engine plugin does it.

Filed RFE #73336 : Unreal: Add ability to select which asset to load when instantiating the HDA.

**Comment by ttvd** [comment]
Has been committed and should be available in 
H15.0/356 

Changes for this commit will be pushed to GitHub on January 15, 2016 EST.

**Comment by JaapSuter** [comment]
You're a machine, that's awesome. Thanks Mykola!
