### ISSUE TITLE
Houdini Engine Installer does not work for custom path installs of Unreal Engine.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#40]
At the moment Houdini Engine installer will place Houdini Engine for UE4 plugin binaries in default locations for both Windows (C:\Program Files\Epic..) and Mac OS X (Users/Shared/UnrealEngine/..).

This will not work when user has a custom path installation (on either system). We would like to detect UE4 installation and place Houdini Engine plugin files correctly.
# 
- [x] Fix Windows installer.
- [x] Fix Mac OS X installer.

**Comment by Yelmond** [comment]
This should be fixed now.
