### ISSUE TITLE
Decoupling Houdini Asset Component from Houdini Actor.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#41]
At the moment we assume that Houdini Component is always attached to Houdini Actor. If it is not attached to one, no cooking or instantiation will take place. We would like to change that. This would be a step towards Blueprint integration as well.
#

**Comment by GeorgeR** [comment]
I've started work on a fork that introduces a HoudiniAssetInstance for just this purpose

**Comment by dpernuit** [comment]
This is exactly what we're doing in v2.
