### ISSUE TITLE
Copying Houdini actor which has instancing data produces a crash.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#47]
Copying instantiated Houdini asset / actor which contains instancing components using ctrv-v/ctrl-c or alt-mouse click produces a crash. PIE / serialization works fine.

This is not UE version specific.

---

Filed as BUG: #74045 : Unreal: Copying Houdini actor which has instancing data produces a crash.

**Comment by cgrebeld** [comment]
Should be fixed now.
