### ISSUE TITLE
Bake generated static meshes as one combined static mesh.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#49]
At the moment we have an option to bake each generated static mesh object (in Houdini Generated Meshes) section. We also have a 'bake all' option, which will bake all generated static meshes individually. We are missing an option to bake all static meshes as one combined static mesh.
# 

Filed as RFE: #74133 : Unreal: Bake generated static meshes as one static mesh.

**Comment by ttvd** [comment]
Related to https://github.com/sideeffects/HoudiniEngineForUnreal/issues/30

**Comment by cgrebeld** [comment]
This seems redundant because you can easily use the **Convert Actors to Static Mesh** or **Merge Actors** functions in the editor once things are baked, or just make your asset merge things on the houdini side.
