### ISSUE TITLE
Add emissive support to generated materials.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#51]
Add emissive support to generated materials. At the moment this is the only one we ignore.

These can be mapped from the following parameters: _emitcolor_texture_, _ogl_emit_, _emitcolor_texture_
- [x] Emissive
  - [x] Uniform support (_ogl_emit_, _emitcolor_, color3).
  - [x] Texture support (_emitcolor_texture_).
# 

Filed as RFE: #74206 : Unreal: Add support for emissive textures.

**Comment by ttvd** [comment]
Related to https://github.com/sideeffects/HoudiniEngineForUnreal/issues/6

**Comment by dpernuit** [comment]
Support of emissive materials was added in 15.5.731
