### ISSUE TITLE
Import of bgeo files into Unreal.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#55]
We would like to be able to import Houdini bgeo files directly into Unreal.
# 

Filed as RFE: #74229 : Ability to import bgeo files into Unreal.

**Comment by varomix** [comment]
I guess you could do an Asset that load a file and it should work, maybe :)

**Comment by ttvd** [comment]
I think the goal was add import to menu. But yeah, you can do it through file sop asset.

**Comment by varomix** [comment]
That would be an Unreal feature not Houdini Engine I guess :)

**Comment by ttvd** [comment]
Well it'd still be done through Houdini Engine, just be exposed in the Editor menu through Houdini Engine plugin hook. I think the HDA to load bgeo files is actually there already.

**Comment by melMass** [comment]
I think this can be closed ? bgeo can be imported through assets easily.

**Comment by dpernuit** [comment]
This can be done easily using a simple "File SOP" HDA indeed.

But the RFE is to be able to import bgeo file directly via the plugin, without the need to instantiate an asset in the world:
In the ContentBrowser: Import a bgeo file will create the corresponding meshes/materials etc.. similar to FBX files.

I'll leave this open as this is something we want to add to version 2.

**Comment by melMass** [comment]
Oh I missed that, that sound like a good idea

**Comment by melMass** [comment]
Oh I missed that, that sound like a good idea

**Comment by dpernuit** [comment]
Indeed added quite a few years ago with v2...
