### ISSUE TITLE
File SOP support for loading file from the web (http://) via HoudiniEngineForUnreal

### ISSUE THREAD

**Issue by robeastham** [sideeffects/HoudiniEngineForUnreal#60]
This might be by design and so not 100% sure I should start an issue for this, but the File SOP within the Houdini Indie interface allows me to load files using http:// instead of a local file path - so .eps and .ai vector files that I'm loading directly from the web work fine.

When I package up my nodes as a digital asset and import into UE4 I get an error in the cook log that says the file cannot be found. Could we get http:// file loading support in Houdini Engine too?

It's possible that this is just an error with the HEFU 4.11 branch that I compiled to work with UE4.11. That's the only UE4 build I currently have Houdini Engine working with.

**Comment by ttvd** [comment]
Hello! Thank you for the bug report. No I think it is an issue in all of plugin versions. We have a check in file parameter which checks wether file is physically present on disk, I believe you are experiencing that. It should be easy to fix, I will look into fixing it ASAP. Thanks!

**Comment by ttvd** [comment]
Hello!

I am unable to reproduce the problem with http links and file parameters. It seems to work on our end.
Please see this asset, it has one parameter, which is an http path to an image.

[http_image_test.zip](https://github.com/sideeffects/HoudiniEngineForUnreal/files/188248/http_image_test.zip)

Please let me know if this works for you.

**Comment by robeastham** [comment]
Apologies, I completely forgot to say that I tried the test file and it appears to work fine. Will investigate again with my file and try and figure out what went wrong. Thanks!
