### ISSUE TITLE
Houdini or Houdini Engine 15.0.439 not available

### ISSUE THREAD

**Issue by varomix** [sideeffects/HoudiniEngineForUnreal#63]
Seems like that version is no longer available to download

help

thanks

**Comment by Yelmond** [comment]
The version specified in the *.Build.cs files is only a minimum version (although is does serve as a maximum - 1 for the previous revision).

Basically, any newer build than 439 should work.

**Comment by varomix** [comment]
ok, the generatefiles script was warning me to download that version specifically

thank you
