### ISSUE TITLE
Crash when a Houdini Input have a invalid static mesh

### ISSUE THREAD

**Issue by gbxmleblanc** [sideeffects/HoudiniEngineForUnreal#65]
It can happen if the static mesh is deleted but the HDAs is not updated.

It crash here:
UStaticMesh \* StaticMesh = HoudiniAssetInstanceInputField->GetInstanceVariation( VariationIdx );

 in UHoudiniAssetInstanceInput::CreateWidget

**Comment by cgrebeld** [comment]
Should be fixed.
