### ISSUE TITLE
Add Support For Mesh Sockets

### ISSUE THREAD

**Issue by grabiller** [sideeffects/HoudiniEngineForUnreal#66]
In the FBX pipeline it is possible to declare Unreal Mesh Sockets through the use of the 'SOCKET' prefix (similar to the use of the UCX prefix).

Could be great to be able to add Null objects inside a Houdini asset, prefixed with 'SOCKET', which would be recognized as Mesh Sockets in Unreal.

**Comment by dpernuit** [comment]
Hi,

Support for mesh Socket was added in 15.5.688.

They can be created by adding points to a group starting with the "socket" prefix.
The sockets rotation and scale can then be defined using the "rot" and "scale" attributes. 
If the rotation attribute is not found, it can be deduced from the  normal ("N") attribute if present.
The socket's name can be defined using the "unreal_mesh_socket_name" attribute.
