### ISSUE TITLE
Module rules files have incorrect path for Houdini on OS X

### ISSUE THREAD

**Issue by admsyn** [sideeffects/HoudiniEngineForUnreal#70]
Both the Editor and Runtime module rules files seem to have the wrong path for Houdini on OS X. Specifically:

https://github.com/sideeffects/HoudiniEngineForUnreal/blob/Houdini16.0-Unreal4.15/Source/HoudiniEngineEditor/HoudiniEngineEditor.Build.cs#L93

and

https://github.com/sideeffects/HoudiniEngineForUnreal/blob/Houdini16.0-Unreal4.15/Source/HoudiniEngineRuntime/HoudiniEngineRuntime.Build.cs#L93

These lines are looking for a Houdini folder named e.g. `16.0.624`, but (at least on my computer) Houdini has installed to a folder named `Houdini16.0.624`.

**Comment by cgrebeld** [comment]
This should be fixed as of bf78066dbff2e3cf732997a27a38e7f34f2daf12
