### ISSUE TITLE
Rebuilding Asset doesn't trigger texture rebake

### ISSUE THREAD

**Issue by dokipen3d** [sideeffects/HoudiniEngineForUnreal#71]
I am using cops to bake textures into houdini. This currently works (apart from the tangents issue which I'll create another github issue next). 

On first instantiation, the textures are created and hooked up but when a parameter is changed in houdini on the cops nodes that generate the texture and the hda is resaved, when unreal rebuilds the asset, the textures aren't updated.

**Comment by dpernuit** [comment]
Hi, thanks for reporting this issue, upon rebuild, the material was still considered as "not changed" so was not updated. I just committed a fix for this issue, it will be available on tomorrow's build of the plug-in ( 16.0.680 )
