### ISSUE TITLE
When baking textures using COPS to ue4, sometimes 1920x1080 is used as resolution

### ISSUE THREAD

**Issue by dokipen3d** [sideeffects/HoudiniEngineForUnreal#72]
I have compositing settings set to use 1024x1024 but when the asset is built in ue4, the res comes in as 1920x1080. It seems to work when the cop network and shop network are outside of the geometry node as the textures come in at the right size, but when a geometry node is hosting the network, then the res iz 1920x1080, at leat from what I can gather from using it.

**Comment by dokipen3d** [comment]
So this is strange. If I host a obj level inside my geo node and put the COP and SHOP inside that, then the Colour map bakes at the right res but the normal map bakes at 1920x1080.

**Comment by dokipen3d** [comment]
I was using a noise and adding which might have padded the 'bounds' that it thinks the comp is set to. If I add a rectangle shape and mask before cooking then the textures come out at the right size.

**Comment by dokipen3d** [comment]
When using a VOP Generator as the first node with the res set explicitly then the res comes through correctly. using a shape causes the wrong res.

**Comment by dpernuit** [comment]
Hi,
Are you also setting the resolution of the shape to 1024x1024  (via override size)?
By default, shapes are created with a 1920x1080 resolution, so compositing one with a 1024x1024 image will cause the result to be 1920x1080.
