### ISSUE TITLE
some parts of the image baked from COPS are black or have rectangular gaps in them

### ISSUE THREAD

**Issue by dokipen3d** [sideeffects/HoudiniEngineForUnreal#73]
example of maps in UE4....

![ue4editor_2017-06-22_23-25-43](https://user-images.githubusercontent.com/7567809/27431918-4b02c65e-57a2-11e7-9c71-cf15aa57d73e.png)
![ue4editor_2017-06-22_23-24-51](https://user-images.githubusercontent.com/7567809/27431853-0d4f9fc6-57a2-11e7-80f6-c0d6b8a223ee.png)

both of these look fine in COPS

![houdinifx_2017-06-22_23-27-37](https://user-images.githubusercontent.com/7567809/27431941-66a13aee-57a2-11e7-96c6-fa7aaa69ce18.png)

**Comment by dokipen3d** [comment]
Not too familiar with HAPI much (only written SOPs and vex functions before).

But RenderCOPToImage and ExtractImageToMemory seem to be relevant fuctions here in HoudiniApi.cpp. Will keep digging.

**Comment by mikelyndon-sesi** [comment]
Hi. Can you share your HDA so we can have a look?

**Comment by dokipen3d** [comment]
Sure here is the one that has gaps/tile artifacts (for some reason github wont allow me to upload a zip)....

https://www.dropbox.com/s/j3kukgle84gi4vi/Rock2.hda?dl=0

And there is also this one which actually manages to crash unreal....

Its a pigs head with a COP texture that uses a SOP trick to get Geometry attributes into COPS layed out in UV space.

https://www.dropbox.com/s/gqze9ixkt3cvmdt/PigHeadCoptextureUnrealCrash.hda?dl=0

This is all in Unreal 4.16, with Houdini 16.0.633 (with its bundles engine plugin) on windows 10.

**Comment by mikelyndon-sesi** [comment]
Thanks for sharing Daniel.  The engineers are pretty swamped at the moment.  We're currently exploring similar workflows though.  Would you be willing to share more information regarding your goals for baking textures in UE4 and which of your issues are show stoppers so we can prioritize on this side.  Feel free to reach out to me at mikel@sidefx.com

**Comment by dokipen3d** [comment]
Hi mike. I've emailed you with more details :)

**Comment by dpernuit** [comment]
Hi,
I submitted a fix for both of the issues (the crash and the incorrect tiles), it should be available on tomorrow's dailybuild ( 16.0.688 ).
The rectangle gaps were actually caused by  an incorrect gamma when cooking constant tiles in the image..

**Comment by dokipen3d** [comment]
Wow thats awesome! Good job! Look forward to using this.
