### ISSUE TITLE
Does not compile with 4.17.1

### ISSUE THREAD

**Issue by maxattack** [sideeffects/HoudiniEngineForUnreal#76]
(using the 4.17 branch)

HoudiniEngineEditor.cpp fails to compile:
#include "IPlacementModeModule.h" - "no such file"

**Comment by cgrebeld** [comment]
I wasn't able to reproduce this issue on my end, but I've committed a change which might fix it for you: 44daa4bc3a17d740eca48ec3ffe18e943b799333
