### ISSUE TITLE
Add support for box and sphere colliders.

### ISSUE THREAD

**Issue by ttvd** [sideeffects/HoudiniEngineForUnreal#8]
Now that we have proper support in Houdini Engine for box and sphere primitives, we would like to add support for those in Unreal plugin.

---
- [x] Add box colliders.
- [x] Add sphere colliders.

---

Filed as RFE #73344: Unreal: Add support for box and sphere colliders.

**Comment by dpernuit** [comment]
Both of these were added via group attributes, as well as convex hulls, and other unreal "simple" colliders.

https://www.sidefx.com/forum/topic/47416/
