### ISSUE TITLE
Issue building 4.20 branch

### ISSUE THREAD

**Issue by OptimisticMonkey** [sideeffects/HoudiniEngineForUnreal#81]
2>f:\Unreal Projects\AMagician\Plugins\HoudiniEngineForUnreal\Source\HoudiniEngineRuntime\Private\HoudiniEngineUtils.cpp(6303): error C4129: 'S': unrecognized character escape sequence

Having issues with:
	FString HoudiniLocation = HOUDINI_ENGINE_HFS_PATH;

Looks like there are some nested macro expansions that for some reason aren't working:

#ifndef HOUDINI_ENGINE_HFS_PATH_DEFINE
#define HOUDINI_ENGINE_HFS_PATH ""
#else
#define HOUDINI_ENGINE_STRINGIFY_HELPER(X) #X
#define HOUDINI_ENGINE_STRINGIFY(X) HOUDINI_ENGINE_STRINGIFY_HELPER(X)
#define HOUDINI_ENGINE_HFS_PATH HOUDINI_ENGINE_STRINGIFY(HOUDINI_ENGINE_HFS_PATH_DEFINE)
#endif

**Comment by OptimisticMonkey** [comment]
For anyone interested - got it working temporarily by hardcoding escaped path:
FString HoudiniLocation = "F:\\\Side\nEffects\nSoftware\\\Houdini\n16.5.536";

Pretty sure it is the annoying spaces in the path causing the issue.

**Comment by timur-losev** [comment]
@OptimisticMonkey here's a PR to fix the issue https://github.com/sideeffects/HoudiniEngineForUnreal/pull/82

**Comment by dpernuit** [comment]
@timur-losev Thanks for the PR.

The fix should be up in tomorrow's daily build, please let us know if you still have issues building the plug-in.
