### ISSUE TITLE
Houdini 16.5.573 no longer available to download on SideFX website resources ( Linux )

### ISSUE THREAD

**Issue by djczaps** [sideeffects/HoudiniEngineForUnreal#83]
Hi 

Can You add 16.5.573 version for Linux to be available to download and install the plugin for HoudiniEngine in Unreal  ?
Maybe updating UE plugin to the newset 16.5.595 would be also possible since it's the newest daily version ?

thanks

Dawid

**Comment by varomix** [comment]
The plugin should work with the latest Houdini version I use it like that, is not really that thigh to version, using a newer version should be ok

**Comment by djczaps** [comment]
Hi back again Varomix ! - it was some time since we spoke last time on the same subject ;)) !
Unfortunatelly it doesn't work with the newer Houdini 16.5.595 
It just saying that there is not compatible with that version after making project files and run UE on Centos 7 here. 

Last version of Houdini I was working with Unreal was 16.5.405 and it was working with older HEngine for that version .

cheers

Dawid

**Comment by varomix** [comment]
I think if the asset was created with an older version there's some issues with versions
I recommend you DON'T update during projects.
If this is with a new project and a newly created HDA then it might be another issue

**Comment by djczaps** [comment]
even without loading the asset it didn't recompile / install correctly under H 16.5.595 Unreal simply wont start complaining about compatibility of Houdini Engine.

**Comment by djczaps** [comment]
ok ... ;(

Just forget to mention that I'm using Apprentice version of Houdini. It allows to create and save digital assets but probably won't allow me to install and use it under Houdini Engine in Unreal. My fault.

**Comment by varomix** [comment]
To create assets for Houdini Engine you need at least Indie as far as I know

**Comment by xDiavalx** [comment]
Dunno if this is still an issue, but this might help:
ftp://ftp.sidefx.com/public/Houdini16.5/
