### ISSUE TITLE
TOPs PDG Support

### ISSUE THREAD

**Issue by leith-bartrich** [sideeffects/HoudiniEngineForUnreal#96]
Just adding this high-level issue to allow it to be tracked.  Currenlty, while there is up-to date houdini 17.5 support, it doesn't implement a solution for TOPs or PDG.  Unless I'm missing something.

**Comment by gaotianpeng** [comment]
i wish the TOPs or PDG for unreal engine coming soon!

**Comment by dpernuit** [comment]
Hi,
Currently, the only way is to use PDG/TOPs with the UE4 plugin is to nest your TOPNet in the HDA.
Version 2 of the plugin will have a PDG asset link, similar to the one we have for unity.

**Comment by gaotianpeng** [comment]
ok, thanks a lot !!!

**Comment by galtza** [comment]
Any ETA for version 2?
