### ISSUE TITLE
How is the Houdini to Unreal Transform handeld?  TranslateHapiTransform?

### ISSUE THREAD

**Issue by Schizo** [sideeffects/HoudiniEngineForUnreal#99]
We are getting mismatches when converting from our right-handed in-house tool into unreal, unfortunately the conversion part isn't in the public repo, is it possible to get the conversion sheet or the snippet of `FHoudiniEngineUtils::TranslateHapiTransform`?

**Comment by dpernuit** [comment]
Hi,
All the plugin's source code is public, and so is that function, see:

https://github.com/sideeffects/HoudiniEngineForUnreal/blob/Houdini17.5-Unreal4.22/Source/HoudiniEngineRuntime/Private/HoudiniEngineUtils.cpp#L438

**Comment by dpernuit** [comment]
But roughly, it ends up being:

Rotation (Quaternion):
Houdini (X,Y,Z,W) => (X,Z,Y,-W) in Unreal

Position
Houdini (X,Y,Z) => (X,Z,Y) * 100 in Unreal 

Scale
Houdini (X,Y,Z) => (X,Z,Y) in Unreal

**Comment by Schizo** [comment]
@dpernuit Ah well, i somehow missed that in the search results. Thanks for that.
